### ISSUE TITLE
[lang] draft specification (or closest thing to it) for developers who want to implement this in another language besides golang?

### ISSUE THREAD

**Issue by dreftymac** [vmware-tanzu/carvel-ytt#67]
Greetings!

* This project looks like a great potential alternative to [jsonnet](https://jsonnet.org/).
* Is a ytt specification on the road-map or currently available somewhere, similar to [jsonnet spec](https://jsonnet.org/ref/spec.html)?

**Comment by cppforlife** [comment]
> This project looks like a great potential alternative to jsonnet.

hey @dreftymac, our intent was definitely to be competitive to jsonnet (thanks for calling out its potential :) ).

> Is a ytt specification on the road-map or currently available somewhere, similar to jsonnet spec?

ytt has two parts: starlark language and yaml/annotation parsing. starlark project (we use go implementation) has a specification that details how language is formed. we do modify starlark library just a tiny bit to add `end` block closers since that's necessary within yaml context.

regarding yaml/annotation parsing part, it currently doesnt not have a separate spec. ytt's implementation is considered canonical.

since this project is young and still developing we did not find necesary for our purposes to define an official spec; however, we are curious to understand how it will be useful for you. are you trying to implement ytt in a different language (and if so, why?), etc.

**Comment by dreftymac** [comment]
**// we are curious to understand how it will be useful for you //**

There are some projects out there with decent credibility that have published specs and a process for community-submitted enhancement proposals. I was just curious where you were in comparison, just to get a feel for the direction you might be wanting to go with YTT. 

**//ytt has two parts: starlark language and yaml/annotation parsing//**

Cool beans, that answers a lot right there. I had not heard about starlark (formerly skylark) until now.

**//we are curious to understand how it will be useful for you//**

Right now it's just preliminary research on whether and the extent to which YTT has the potential to go toe-to-toe with JSONnet (and similar projects) ... YAML-based tools are powerful, but they do not get as much buzz as JSON in most contexts. 

I think there is a lot of room for tools like this to take off and gain more prominence, but it is not obvious how to move forward in promoting and developing this kind of tool, or which workflows it is best suited to augment or disrupt. 

// since this project is young and still developing we did not find necesary for our purposes to define an official spec //

That makes sense. The mere fact that you are building on both YAML and starlark means you have an implicit spec at very least (except of course to the extent that you diverge from those projects).

In any event, I applaud the progress you've made so far and think it's a great idea. Thanks for the additional information!
